// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import model "github.com/icelandicicecream/ben-portfolio-v2/model"

var projects = []model.ProjectCard{
	{
		// Create a write-up
		Title:       "AI Powered Accounting Software",
		Tags:        []string{"Go", "Svelte Kit", "PostgreSQL", "OpenAI API"},
		Date:        "Oct 25, 2024",
		Description: "An accounting software with a built-in AI interface to creating transactions and understanding your accounting data",
		Link:        "https://ben-ghost-blog.fly.dev/building-an-accounting-software-from-scratch-2/",
	},
	{
		Title:       "Self Hosted Blog",
		Tags:        []string{"Docker", "Ghost", "Fly"},
		Date:        "Oct 25, 2024",
		Description: "A self hosted blog built with Ghost and Fly.io. I built this to learn more about the platform and how to deploy a blog.",
		Link:        "https://ben-ghost-blog.fly.dev/",
	},
	{
		// Create a write-up
		Title:       "OpenAI Go Chat Bot",
		Tags:        []string{"Go", "OpenAI API", "Svelte"},
		Date:        "Feb 25, 2024",
		Description: "A functioning chat bot that utilises OpenAI's API for Chat Completions using Go and Svelte.",
		Link:        "https://github.com/IcelandicIcecream/go-openai-web",
	},
	{
		// Create a write-up
		Title:       "Go Discord Music Bot",
		Tags:        []string{"Go", "Discord API", "Youtube API"},
		Date:        "Aug 6, 2023",
		Description: "A discord bot that plays music from youtube I built for my gaming sessions with my friends on discord.",
		Link:        "https://ben-ghost-blog.fly.dev/building-a-discord-music-bot-with-go/",
	},
	{
		// Create a write-up
		Title:       "Accounting Database Management Platform",
		Tags:        []string{"Go", "Svelte Kit", "PostgreSQL"},
		Date:        "Jun 25, 2023 - Present",
		Description: "An accounting software that consolidates data from multiple sources, standardises them and generates reports from it. ",
		Link:        "https://ben-ghost-blog.fly.dev/creating-an-accounting-database-management-platform/",
	},
	{
		Title:       "Single Release Landing Page",
		Tags:        []string{"NextJS", "React", "TailwindCSS"},
		Date:        "Apr 12, 2023",
		Description: "A landing page for a musical artist single release. Made it in style of the 2000s, with a retro design.",
		Link:        "https://talitha-6hrs.vercel.app/",
	},
	{
		Title:       "First Portfolio Website",
		Tags:        []string{"NextJS", "React", "TailwindCSS"},
		Date:        "Sep 8, 2022",
		Description: "My first portfolio website. I made it back when I tried learning NextJS and React",
		Link:        "https://icelandicicecream.vercel.app/",
	},
	{
		Title:       "Teh Ultimate Bill Splitter",
		Tags:        []string{"React", "Vercel"},
		Date:        "Aug 30, 2022",
		Description: "A real-time bill splitting single-page application made to handle tax, discounts and delivery fees.",
		Link:        "https://tehlunchcalculator.vercel.app",
	},
	{
		Title:       "Music Company Website",
		Tags:        []string{"Wordpress", "Woocommerce", "CSS"},
		Date:        "Dec 20, 2020",
		Description: "A business site meant to showcase the company's services, artists and handle merch transactions via stripe and woocommerce.",
		Link:        "https://breakingmusic.my/",
	},
}

func ProjectList(state model.State) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-white py-8 sm:py-14 shadow-lg ring-1 ring-gray-900/5 rounded-xl sm:rounded-md bg-opacity-40\"><div class=\"mx-auto max-w-7xl px-6 lg:px-12\"><h2 class=\"text-4xl font-bold tracking-tight text-gray-600 pl-4\">Projects</h2><p class=\"mt-2 text-3xl leading-8 text-gray-600 pl-4 lg:text-lg\">Here are the projects that I've worked on recently</p><!-- Scrollable container --><div class=\"mt-8 overflow-y-auto max-h-[600px]\"><div class=\"divide-y divide-gray-200\"><!-- Loop through projects -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, project := range projects {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<article class=\"flex flex-col items-start justify-between p-4 lg:max-w-xl\"><div class=\"mb-4 flex items-center gap-x-4 text-xl mt-6 lg:text-xs\"><time class=\"text-gray-500 text-2xl lg:text-xs\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(project.Date)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/projectsList.templ`, Line: 86, Col: 70}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</time> <span class=\"flex flex-row items-center gap-x-2 text-2xl lg:text-xs\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, tag := range project.Tags {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"relative z-10 rounded-md bg-teal-50 shadow-sm px-3 py-3 font-medium text-gray-600 hover:bg-teal-100 lg:py-1.5\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(tag)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/projectsList.templ`, Line: 89, Col: 136}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></div><div class=\"group relative\"><h3 class=\"mb-4 text-3xl font-semibold leading-10 text-gray-600 group-hover:text-gray-600 lg:text-lg lg:mb-2\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 templ.SafeURL = project.Link
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var4)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" target=\"_blank\" rel=\"noopener noreferrer\"><span class=\"absolute inset-0\"></span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(project.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/projectsList.templ`, Line: 97, Col: 25}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a></h3><p class=\"mb-4 line-clamp-3 text-3xl leading-10 text-gray-600 lg:text-sm\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(project.Description)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/projectsList.templ`, Line: 100, Col: 103}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
