// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func TypingEffect(word, id string, delay int) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_TypingEffect_28bb`,
		Function: `function __templ_TypingEffect_28bb(word, id, delay){let index = 0;
	const displayArea = document.getElementById(id)

  const intervalId = setInterval(function () {
    if (index < word.length) {
      displayArea.textContent += word[index]
      index++
    } else {
      clearInterval(intervalId)
    }
  }, delay);
}`,
		Call:       templ.SafeScript(`__templ_TypingEffect_28bb`, word, id, delay),
		CallInline: templ.SafeScriptInline(`__templ_TypingEffect_28bb`, word, id, delay),
	}
}
